name: Run tests

on:   [pull_request]

jobs: 
  MyTests:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: tb

      - name: Move tb dir
        run:  mv tb ~
        
      - name: Execute All Tests
        run:  |
              sudo apt-get update
              sudo apt install python3
              sudo apt install python3-pip
              pip3 install vk_api
              pip3 install vk_api
              cd ~/tb
              pip3 install -r requirements.txt
              sudo python3 utests.py
