name: Run tests

on:   [pull_request]

jobs: 
  MyTests:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: tb

      - name: Move tb dir
        run:  mv tb ~
        
      - name: Tests and lint
        run:  |
              sudo apt-get update
              sudo apt install python3
              sudo apt install python3-pip
              
              # installing necessary libraries
              pip3 install vk_api
              sudo mv /home/runner/.local/lib/python3.8/site-packages/vk_api /usr/lib/python3/dist-packages
              sudo mv /home/runner/.local/lib/python3.8/site-packages/vk_api-11.9.7.dist-info /usr/lib/python3/dist-packages
              sudo mv /home/runner/.local/lib/python3.8/site-packages/jconfig /usr/lib/python3/dist-packages
              cd ~/tb
              pip3 install -r requirements.txt
              
              # installing pylint
              pip3 install pylint
              
              # pylint checs for only errors
              pylint app.py --disable=all --enable=E
              pylint methods.py --disable=all --enable=E
              pylint utests.py --disable=all --enable=E
              sudo docker build -t docker-check .
              
              # running tests
              sudo python3 utests.py
